name    'creamce'
version '0.0.1'
author 'schwicke'
license 'Apache License, Version 2.0 (the "License")'
summary 'Resources for managing an EMI cream CE service'
description 'This modules provides classes and definitions required to manage and properly configure an EMI creamce service.'
project_page 'http://www.eu-emi.eu/'
dependency 'puppetlabs/stdlib'
